<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\RJ.Api\RJ.Api.csproj" />
    <ProjectReference Include="..\..\src\RJ.Application\RJ.Application.csproj" />
    <ProjectReference Include="..\..\src\RJ.BenchmarkCli\RJ.BenchmarkCli.csproj" />
    <ProjectReference Include="..\..\src\RJ.Domain\RJ.Domain.csproj" />
    <ProjectReference Include="..\..\src\RJ.Infrastructure\RJ.Infrastructure.csproj" />
  </ItemGroup>
</Project>
